# Generated by Django 5.2.7 on 2025-10-20 07:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.URLField(primary_key=True, serialize=False)),
                ('host', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('web', models.URLField(blank=True)),
                ('profileImage', models.ImageField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBkA9WO3FnL4fddebhCcTztCr6vr2METdo9w&s', upload_to='profile_pics/')),
                ('username', models.CharField(default='goldenuser', max_length=50, unique=True)),
                ('password', models.CharField(default='goldenpassword', max_length=50)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_admin', models.BooleanField(default=False)),
                ('followers_info', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField()),
                ('following', models.ManyToManyField(blank=True, related_name='followers_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.URLField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(default='entry', editable=False, max_length=20)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('web', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('contentType', models.CharField(default='text/plain', max_length=100)),
                ('content', models.TextField()),
                ('source', models.URLField(blank=True)),
                ('origin', models.URLField(blank=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('UNLISTED', 'Unlisted'), ('FRIENDS', 'Friends-Only'), ('DELETED', 'Deleted')], default='PUBLIC', max_length=10)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('is_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.URLField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(default='comment', editable=False, max_length=20)),
                ('contentType', models.CharField(default='text/markdown', max_length=100)),
                ('comment', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='golden.comments')),
                ('entry', models.ForeignKey(db_column='entry_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='golden.entry')),
            ],
        ),
        migrations.CreateModel(
            name='EntryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='entry_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='golden.entry')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.URLField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(default='follow', editable=False, max_length=20)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('object', models.URLField()),
                ('state', models.CharField(choices=[('REQUESTING', 'requesting'), ('ACCEPTED', 'accepted'), ('REJECTED', 'rejected')], default='REQUESTING', max_length=20)),
                ('published', models.DateTimeField()),
                ('actor', models.ForeignKey(db_column='actor_id', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_follow_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.URLField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(default='like', editable=False, max_length=20)),
                ('object', models.URLField()),
                ('published', models.DateTimeField()),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.URLField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('remote_nodes', models.JSONField(blank=True, default=list)),
                ('admins', models.ManyToManyField(blank=True, related_name='admin_of_nodes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
