# Generated by Django 5.2.7 on 2025-10-18 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.URLField(primary_key=True, serialize=False, unique=True)),
                ('host', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('web', models.URLField(blank=True)),
                ('profileImage', models.URLField(blank=True)),
                ('userName', models.CharField(default='temp_user', max_length=100, unique=True)),
                ('password', models.CharField(default='temp_pass', max_length=20)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('followers_info', models.JSONField(blank=True, default=dict)),
                ('following', models.ManyToManyField(blank=True, related_name='followers_set', to='golden.author')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.URLField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(default='entry', editable=False, max_length=20)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('web', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('contentType', models.CharField(default='text/plain', max_length=100)),
                ('content', models.TextField()),
                ('source', models.URLField(blank=True)),
                ('origin', models.URLField(blank=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('UNLISTED', 'Unlisted'), ('FRIENDS', 'Friends-Only'), ('DELETED', 'Deleted')], default='PUBLIC', max_length=10)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='golden.author')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.URLField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(default='comment', editable=False, max_length=20)),
                ('contentType', models.CharField(default='text/markdown', max_length=100)),
                ('comment', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='golden.author')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='golden.comments')),
                ('entry', models.ForeignKey(db_column='entry_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='golden.entry')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.URLField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(default='follow', editable=False, max_length=20)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('object', models.URLField()),
                ('state', models.CharField(choices=[('REQUESTING', 'requesting'), ('ACCEPTED', 'accepted'), ('REJECTED', 'rejected')], default='REQUESTING', max_length=20)),
                ('published', models.DateTimeField()),
                ('actor', models.ForeignKey(db_column='actor_id', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_follow_requests', to='golden.author')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.URLField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(default='like', editable=False, max_length=20)),
                ('object', models.URLField()),
                ('published', models.DateTimeField()),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='golden.author')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.URLField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('remote_nodes', models.JSONField(blank=True, default=list)),
                ('admins', models.ManyToManyField(blank=True, related_name='admin_of_nodes', to='golden.author')),
            ],
        ),
    ]
