<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-11-17 05:14
=======
# Generated by Django 5.2.8 on 2025-11-17 04:45
>>>>>>> 5d373ef320496bfff9cf673327d5c57455e7c248

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.URLField(primary_key=True, serialize=False, unique=True)),
                ('host', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('web', models.URLField(blank=True)),
                ('profileImage', models.ImageField(default='profile_pics/default_profile.webp', upload_to='profile_pics/')),
                ('username', models.CharField(default='goldenuser', max_length=50, unique=True)),
                ('password', models.CharField(default='goldenpassword', max_length=128)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('following', models.ManyToManyField(blank=True, related_name='followers_set', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.URLField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(default='entry', editable=False, max_length=20)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('web', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('contentType', models.CharField(default='text/plain', max_length=100)),
                ('content', models.TextField()),
                ('source', models.URLField(blank=True)),
                ('origin', models.URLField(blank=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('UNLISTED', 'Unlisted'), ('FRIENDS', 'Friends-Only'), ('DELETED', 'Deleted')], db_index=True, default='PUBLIC', max_length=10)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('is_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.URLField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(default='comment', editable=False, max_length=20)),
                ('content', models.TextField(blank=True, max_length=200)),
                ('contentType', models.CharField(default='text/markdown', max_length=100)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='golden.comment')),
                ('entry', models.ForeignKey(db_column='entry_id', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='golden.entry')),
            ],
        ),
        migrations.CreateModel(
            name='EntryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='entry_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='golden.entry')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.URLField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(default='follow', editable=False, max_length=20)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('object', models.URLField()),
                ('state', models.CharField(choices=[('REQUESTED', 'requested'), ('ACCEPTED', 'accepted'), ('REJECTED', 'rejected')], db_index=True, default='REQUESTING', max_length=20)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(db_column='actor_id', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_follow_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.URLField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(default='like', editable=False, max_length=20)),
                ('object', models.URLField(db_index=True)),
                ('published', models.DateTimeField()),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.URLField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('auth_user', models.CharField(blank=True, max_length=100, null=True)),
                ('auth_pass', models.CharField(blank=True, max_length=100, null=True)),
                ('admins', models.ManyToManyField(blank=True, related_name='admin_of_nodes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KnownNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_nodes', to='golden.node')),
            ],
        ),
    ]
