# Generated by Django 5.2.7 on 2025-10-30 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.URLField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(default='comment', editable=False, max_length=20)),
                ('content', models.TextField(blank=True, max_length=200)),
                ('contentType', models.CharField(default='text/markdown', max_length=100)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(db_column='entry_id', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='golden.entry')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='golden.comment')),
            ],
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
