# Generated by Django 5.2.7 on 2025-10-17 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment_string',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='posted',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='posted',
            new_name='published',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='post',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='updated',
        ),
        migrations.AddField(
            model_name='author',
            name='followers_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='author',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers_set', to='golden.author'),
        ),
        migrations.AddField(
            model_name='author',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='host',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='password',
            field=models.CharField(default='temp_pass', max_length=20),
        ),
        migrations.AddField(
            model_name='author',
            name='profileImage',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='userName',
            field=models.CharField(default='temp_user', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='author',
            name='web',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='contentType',
            field=models.CharField(default='text/markdown', max_length=100),
        ),
        migrations.AddField(
            model_name='comments',
            name='entry',
            field=models.ForeignKey(db_column='entry_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='golden.entry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='type',
            field=models.CharField(default='comment', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='entry',
            name='contentType',
            field=models.CharField(default='text/plain', max_length=100),
        ),
        migrations.AddField(
            model_name='entry',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='origin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='source',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='entry',
            name='type',
            field=models.CharField(default='entry', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='entry',
            name='web',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='node',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_of_nodes', to='golden.author'),
        ),
        migrations.AddField(
            model_name='node',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='node',
            name='remote_nodes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='node',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.URLField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='golden.author'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.URLField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.URLField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.URLField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(default='follow', editable=False, max_length=20)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('object', models.URLField()),
                ('state', models.CharField(choices=[('REQUESTING', 'requesting'), ('ACCEPTED', 'accepted'), ('REJECTED', 'rejected')], default='REQUESTING', max_length=20)),
                ('published', models.DateTimeField()),
                ('actor', models.ForeignKey(db_column='actor_id', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_follow_requests', to='golden.author')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.URLField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(default='like', editable=False, max_length=20)),
                ('object', models.URLField()),
                ('published', models.DateTimeField()),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='golden.author')),
            ],
        ),
    ]
