# Generated by Django 5.2.7 on 2025-11-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.ImageField(default='profile_pics/default_profile.png', upload_to='profile_pics/'),
        ),
    ]
