# Generated by Django 5.2.7 on 2025-11-03 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryimage',
            name='name',
            field=models.CharField(blank=True, help_text='Optional: rename the file for admin-friendly URLs', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.URLField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='entryimage',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='golden.entry'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.URLField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(default='comment', editable=False, max_length=20)),
                ('content', models.TextField(blank=True, max_length=200)),
                ('contentType', models.CharField(default='text/markdown', max_length=100)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(db_column='entry_id', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='golden.entry')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='golden.comment')),
            ],
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
