# Generated by Django 5.2.7 on 2025-11-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.FileField(default='profile_pics/default_profile.webp', upload_to='profile_pics/'),
        ),
    ]
