# Generated by Django 5.2.7 on 2025-10-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='posted',
            new_name='is_posted',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='updated',
            new_name='is_updated',
        ),
        migrations.AddField(
            model_name='author',
            name='followers_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='author',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers_set', to='golden.author'),
        ),
        migrations.AddField(
            model_name='author',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='author',
            name='password',
            field=models.CharField(default='goldenpassword', max_length=50),
        ),
        migrations.AddField(
            model_name='author',
            name='userName',
            field=models.CharField(default='goldenuser', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
