# Generated by Django 5.2.7 on 2025-11-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_shadow',
            field=models.BooleanField(default=False),
        ),
    ]
