# Generated by Django 5.2.7 on 2025-11-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0002_entryimage_name_alter_author_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='password',
            field=models.CharField(default='goldenpassword', max_length=128),
        ),
    ]
