# Generated by Django 5.2.6 on 2025-11-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0002_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_active',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
