# Generated by Django 5.2.7 on 2025-10-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0002_author_email_author_groups_author_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='friends',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
