# Generated by Django 5.2.7 on 2025-11-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0002_inbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_local',
            field=models.BooleanField(default=True),
        ),
    ]
