# Generated by Django 5.2.7 on 2025-11-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0003_author_is_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='is_local',
        ),
        migrations.RemoveField(
            model_name='author',
            name='is_shadow',
        ),
    ]
