# Generated by Django 5.2.6 on 2025-11-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0003_node_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
