# Generated by Django 5.2.7 on 2025-11-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0004_remove_author_is_local_remove_author_is_shadow'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
