# Generated by Django 5.2.7 on 2025-11-17 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0002_author_is_shadow'),
        ('golden', '0002_comment_likes_node_is_active'),
        ('golden', '0005_comment_likes'),
    ]

    operations = [
    ]
