# Generated by Django 5.2.7 on 2025-11-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0005_inbox_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='id',
            field=models.URLField(primary_key=True, serialize=False),
        ),
    ]
