# Generated by Django 5.2.7 on 2025-11-20 20:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golden', '0006_alter_inbox_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
